from pptx import Presentation
from models import PresentationData
import os
import uuid

def create_pptx_file(data: PresentationData) -> str:
    print(f"🎨 [Render] 正在渲染 PPT: {data.topic}...")
    
    # --- 渲染PPT在这里写核心逻辑 ---
    # 目前先创建一个空的 PPT
    prs = Presentation("template.pptx") 
    
    # 简单加一页，证明代码跑通了
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = data.topic
    slide.placeholders[1].text = "Generated by AI Backend"
    
    # 生成唯一文件名
    filename = f"{uuid.uuid4()}.pptx"
    save_path = os.path.join("generated_ppts", filename)
    
    # 确保目录存在
    os.makedirs("generated_ppts", exist_ok=True)
    
    prs.save(save_path)
    print(f"✅ [Render] 文件保存至: {save_path}")
    
    return filename