# main_backend.py
import json
import time
import os
import requests
from io import BytesIO
from pptx import Presentation
from pptx.util import Pt, Inches
from pptx.dml.color import RGBColor
from openai import OpenAI

# === 1. 定义数据结构与 LLM 接口 ===
def get_content_from_llm(topic, use_ai=False):
    # --- 1.1 模拟模式 (Mock) ---
    if not use_ai:
        print("(测试模式) 使用预设数据，包含网络图片关键词...")
        time.sleep(0.5)
        return {
            "title": f"{topic} 深度解析",
            "subtitle": "Generated by AI Generator",
            "pages": [
                {
                    "type": "text",
                    "title": "背景介绍",
                    "content": ["传统模式效率低下", "数字化转型势在必行", "AI 赋能全流程"]
                },
                {
                    "type": "image",
                    "title": "概念演示图",
                    # 这里不再写死文件名，而是给一个英文关键词
                    "image_query": "futuristic data center cyberpunk style", 
                    "caption": "未来数据中心概念图"
                },
                {
                    "type": "table",
                    "title": "数据对比",
                    "table_data": {
                        "headers": ["指标", "传统方式", "AI 方式"],
                        "rows": [["耗时", "5天", "1分钟"], ["成本", "高昂", "低廉"]]
                    }
                }
            ]
        }

    # --- 1.2 AI 模式 (调用 OpenAI) ---
    print(f"🤖 (AI 模式) 正在请求 OpenAI 构思 PPT 内容...")
    
    #  Key
    api_key = "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" 
    client = OpenAI(api_key=api_key)
    
    # 核心 Prompt：教 AI 如何返回 JSON
    prompt = f"""
    你是一个专业的 PPT 生成助手。请为主题 "{topic}" 生成 4-5 页 PPT 内容。
    
    输出必须是纯 JSON 格式，不要包含 Markdown 标记（如 ```json）。
    JSON 结构要求：
    {{
        "title": "PPT主标题",
        "subtitle": "副标题",
        "pages": [
            {{ 
                "type": "text", 
                "title": "页标题", 
                "content": ["要点1", "要点2", "要点3"] 
            }},
            {{
                "type": "image",
                "title": "页标题",
                "image_query": "这里写一个描述该页面内容的英文关键词，用于生成图片，例如 'business meeting'",
                "caption": "图片下方的说明文字"
            }},
            {{
                "type": "table",
                "title": "对比分析",
                "table_data": {{
                    "headers": ["列1", "列2", "列3"],
                    "rows": [["A1", "B1", "C1"], ["A2", "B2", "C2"]]
                }}
            }}
        ]
    }}
    请确保至少包含 1 页 image 类型和 1 页 table 类型。
    """
    
    try:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo", # 如果你有 gpt-4，建议改成 gpt-4-turbo，JSON 格式更稳
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7
        )
        content = response.choices[0].message.content
        # 清理可能存在的 markdown 符号
        content = content.replace("```json", "").replace("```", "")
        return json.loads(content)
    except Exception as e:
        print(f"OpenAI 调用或解析失败: {e}")
        return None


# === 2. 字体与排版 ===
def auto_fit_text(text_frame, content_list, font_name="Microsoft YaHei"):
    text_frame.clear()
    total_chars = sum([len(line) for line in content_list])
    
    if total_chars > 200: font_size = Pt(14)
    elif total_chars > 100: font_size = Pt(18)
    else: font_size = Pt(24)

    for line in content_list:
        p = text_frame.add_paragraph()
        p.text = line
        p.font.size = font_size
        p.font.name = font_name
        p.space_after = Pt(10)


# === 3. 下载网络图片 ===
def get_image_stream(query):
    """
    尝试从 AI 接口下载图片。如果失败，自动降级使用随机风景图。
    """
    # 1. 准备请求头 (假装自己是浏览器，防止被拦截)
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    }

    # 2. 定义图片源
    safe_query = query.replace(" ", "%20")
    # 首选：AI 生成源
    url_primary = f"https://image.pollinations.ai/prompt/{safe_query}?width=1280&height=720&nologo=true"
    # 备选：随机风景源 (如果不通，就用这个兜底)
    url_backup = "https://picsum.photos/1280/720"

    print(f"   ⬇️ 正在下载图片: {query} ...")
    
    # 3. 尝试下载 (主源)
    try:
        response = requests.get(url_primary, headers=headers, timeout=10)
        if response.status_code == 200:
            return BytesIO(response.content)
        else:
            print(f"   ⚠️ AI 图片源失败 (状态码 {response.status_code})，尝试备用源...")
    except Exception as e:
        print(f"   ⚠️ AI 图片源连接错误: {e}")

    # 4. 尝试下载 (备用源)
    try:
        print(f"   🔄 正在切换到备用图片源 (Picsum)...")
        response = requests.get(url_backup, headers=headers, timeout=10)
        if response.status_code == 200:
            return BytesIO(response.content)
    except Exception as e:
        print(f"   ❌ 备用源也失败了: {e}")

    return None


# === 4. 页面生成逻辑 ===
def create_table_slide(slide, data, font_name):
    left = Inches(1); top = Inches(2); width = Inches(8); height = Inches(4)
    headers = data.get("headers", [])
    rows = data.get("rows", [])
    if not headers: return

    shape = slide.shapes.add_table(len(rows)+1, len(headers), left, top, width, height)
    table = shape.table

    # 表头
    for i, h in enumerate(headers):
        cell = table.cell(0, i)
        cell.text = str(h)
        cell.fill.solid()
        cell.fill.fore_color.rgb = RGBColor(0, 112, 192)
        for p in cell.text_frame.paragraphs:
            p.font.name = font_name
            p.font.bold = True
            p.font.color.rgb = RGBColor(255, 255, 255)

    # 内容
    for r_idx, row in enumerate(rows):
        for c_idx, val in enumerate(row):
            cell = table.cell(r_idx+1, c_idx)
            cell.text = str(val)
            for p in cell.text_frame.paragraphs:
                p.font.name = font_name
                p.font.size = Pt(14)

def create_image_slide(slide, image_query, caption, font_name):
    # 1. 下载图片流
    image_stream = get_image_stream(image_query)
    
    if not image_stream:
        # 如果下载失败就放一个文本框提示
        txBox = slide.shapes.add_textbox(Inches(3), Inches(3), Inches(4), Inches(1))
        txBox.text_frame.text = f"[ 图片下载失败: {image_query} ]"
        return

    # 2. 插入图片
    left = Inches(1.5); top = Inches(2); height = Inches(4.5)
    slide.shapes.add_picture(image_stream, left, top, height=height)

    # 3. 添加说明
    if caption:
        txBox = slide.shapes.add_textbox(Inches(1.5), Inches(6.6), Inches(7), Inches(1))
        p = txBox.text_frame.add_paragraph()
        p.text = caption
        p.font.size = Pt(12)
        p.font.italic = True
        p.font.name = font_name


# === 5. 主入口 ===
def generate_ppt_file(topic, output_filename="final_output.pptx", template_path="template.pptx", font_name="Microsoft YaHei", use_ai=False):
    
    data = get_content_from_llm(topic, use_ai=use_ai)
    if not data: return None

    if os.path.exists(template_path):
        prs = Presentation(template_path)
    else:
        prs = Presentation()

    # 封面
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    if slide.shapes.title: 
        slide.shapes.title.text = data.get("title", "")
        for p in slide.shapes.title.text_frame.paragraphs: p.font.name = font_name
    
    if len(slide.placeholders) > 1:
        try: slide.placeholders[1].text = data.get("subtitle", "")
        except: pass

    # 内容页
    layout_idx = 1 if len(prs.slide_layouts) > 1 else 0
    
    for page in data.get("pages", []):
        slide = prs.slides.add_slide(prs.slide_layouts[layout_idx])
        
        # 标题
        if slide.shapes.title:
            slide.shapes.title.text = page.get("title", "")
            for p in slide.shapes.title.text_frame.paragraphs: p.font.name = font_name
        
        p_type = page.get("type", "text")
        
        if p_type == "text":
            if len(slide.placeholders) > 1:
                auto_fit_text(slide.placeholders[1].text_frame, page.get("content", []), font_name)
        
        elif p_type == "table":
            create_table_slide(slide, page.get("table_data", {}), font_name)
            
        elif p_type == "image":
            # 传入 image_query 而不是 path
            query = page.get("image_query", "technology")
            caption = page.get("caption", "")
            create_image_slide(slide, query, caption, font_name)

    try:
        prs.save(output_filename)
        print(f"PPT生成完毕: {output_filename}")
        return output_filename
    except Exception as e:
        print(f"保存异常: {e}")
        return None